name: Generate Multiple Newspapers to Drive

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 6 * * *' # 7:30 italiane

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Generate PDFs with Goosepaper
        run: |
          set -e
          docker pull ghcr.io/claudiotomasi/goosepaper:latest

          CONFIGS=("news" "news2")

          for TYPE in "${CONFIGS[@]}"; do
            echo "=========================================="
            echo "Inizio elaborazione: $TYPE"

            mkdir -p out/$TYPE

            timeout 10m docker run --rm --init \
              -v ${{ github.workspace }}:/mount \
              ghcr.io/claudiotomasi/goosepaper:latest \
              -c /mount/${TYPE}.json \
              -o /mount/out/$TYPE/${TYPE}_${{ env.DATE }}.pdf

            echo "Fine elaborazione: $TYPE"
            sleep 2
          done

      - name: Upload PDFs to Google Drive (dated folder)
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_GDRIVE_TYPE: drive
          RCLONE_CONFIG_GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          RCLONE_CONFIG_GDRIVE_TOKEN: ${{ secrets.RCLONE_CONFIG_PASS }}
          RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID: "1DtC3Da1Q1-TY8TBVbFXmHn9lDgSb_ehA"
        with:
          args: 'copy ./out gdrive:${{ env.DATE }} --include "*.pdf"'
