name: Generate Newspaper to Drive
on: 
  workflow_dispatch: # Questo ti permette di lanciarlo a mano per testare

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Run Goosepaper
        run: |
          docker run -v ${{ github.workspace }}:/mount ghcr.io/claudiotomasi/goosepaper:latest \
          goosepaper -c /mount/example-config.json -o /mount/Giornale_${{ env.DATE }}.pdf

      - name: Upload to Drive
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_GDRIVE_TYPE: drive
          RCLONE_CONFIG_GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          RCLONE_CONFIG_GDRIVE_TOKEN: ${{ secrets.RCLONE_CONFIG_PASS }}
          # QUI INCOLLA L'ID DELLA CARTELLA CHE HAI PRESO AL PASSO 1
          RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID: "1DtC3Da1Q1-TY8TBVbFXmHn9lDgSb_ehA"
        with:
          args: copy "Giornale_${{ env.DATE }}.pdf" gdrive: