name: Get reMarkable Token
on:
  workflow_dispatch:
    inputs:
      rm_code:
        description: 'Codice di 8 lettere da my.remarkable.com'
        required: true

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        run: |
          pip install rmapy
          python -c "
          import rmapy.api
          rm = rmapy.api.Client()
          try:
              # La registrazione restituisce direttamente il token
              token = rm.register_device('${{ github.event.inputs.rm_code }}')
              print('\n' + '*' * 40)
              print('IL TUO DEVICE TOKEN E:')
              print(token)
              print('*' * 40 + '\n')
          except Exception as e:
              print(f'Errore durante la registrazione: {e}')
          "