name: Get reMarkable Token
on:
  workflow_dispatch:
    inputs:
      rm_code:
        description: 'Inserisci il codice di 8 lettere di reMarkable'
        required: true

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        run: |
          # Scarichiamo l'ultima versione di rMview o un client compatibile
          # In questo caso usiamo un semplice script python che parla con le nuove API
          pip install rmapy
          python -c "
          from rmapy.api import rMapi
          rm = rMapi()
          token = rm.register_device('${{ github.event.inputs.rm_code }}')
          print('*****************************************')
          print('IL TUO DEVICE TOKEN E:')
          print(token)
          print('*****************************************')
          "